# Generated by Django 4.1.1 on 2022-09-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_crud', '0002_post_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='direction',
            field=models.TextField(),
        ),
    ]
